### ISSUE TITLE
[Feature request] Option to disable colours

### ISSUE THREAD

**Issue by Hund** [laktak/rsyncy#10]
It would be nice if there was an option to disable the colours, or of it would at least respect the colours that I'm using.

I'm using the Solarized colours, and it doesn't look that good for me. :)

Thank you for an awesome piece of software!

**Comment by laktak** [comment]
No sure how I can respect your colors ;)

Can you try to run it with `COLORTERM='' TERM=xterm` to use the 16 colors defined by your terminal. Does that work better for you?

**Comment by Hund** [comment]
That works for me. :)

**Comment by laktak** [comment]
http://no-color.org/ is now supported as well
