### ISSUE TITLE
ctrl-C interrupting is broken: `rsync` returns exit status `20` to shell, but `rsyncy` returns no-error `0` ("SIGINT/SIGTERM/SIGHUP (code 20)")

### ISSUE THREAD

**Issue by dwawlyn** [laktak/rsyncy#11]
When you interrupt plain `rsync` with ctrl-C, it prints an error message like:
```
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(642) [sender=3.1.3]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(504) [generator=3.1.3]
```
and indeed returns an exit status of `20` to the shell.

However, when you interrupt `rsyncy`,
it lets `rsync` print that same error message to the screen,
**but returns the non-error exit status of `0` to the shell instead**.

---
(
Sorry, this looks like something that's probably really easy to fix,
but I just don't know anywhere near enough about python to figure out the documentation for this.
(Also, sorry if I'm somehow asking in the wrong place; I'm kinda new to all this...)

I assume this I got from `pip list` is accurate:
```
Package             Version
rsyncy              0.1.0
```
and there's nothing relevantly weird or outdated about my specific copy.
)

---

Thanks!

**Comment by laktak** [comment]
Thanks, I'll look into it.

**Comment by dwawlyn** [comment]
Thanks!

I figured *maybe* I could just hack it myself,
but... yeah I don't really know where to start.

I bet it's conceptually pretty simple,
but I *barely* learned python, years ago, and I've forgotten most of what little I did know,
so I don't really know how to figure out the documentation.

Like, I would *guess* I should be looking at the line:
`rc.put(p.returncode)`
which I think ends up functionally running as:
`queue.Queue().put(p.returncode)`
and/or the:
`sys.exit(rc.get())`
at the very end,
but beyond that, I really don't know how to figure it out.

I was actually gonna ask about it on stackexchange
(something like "Get commandline python script that calls another commandline program `foo` to return exit status of `foo` to shell?")
and I wrote the question out,
but still haven't gotten around to posting it cuz... juggling other things combined with irrational social anxiety or something?

**Comment by laktak** [comment]
Can you test it with 0.2.0?

**Comment by dwawlyn** [comment]
Bingo bango it works! Thank you so much! :D

**Comment by laktak** [comment]
It was a bit late yesterday so I didn't notice your previous comment ;) Anyways, glad it works :)
