### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by kiblik** [laktak/rsyncy#12]
Thank you for this project. Is it possible to add support for `arm64`? I wanted to install it on Raspberry PI but I wasn't successful.

It is not possible via APT:
```bash
...
# apt search rsyncy
Sorting... Done
Full Text Search... Done
rsyncy/unknown 0.2.0-1 amd64
  Status/progress bar for rsync
# apt install rsyncy
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package rsyncy
```

And direct installation as well
```bash
# wget https://download.opensuse.org/repositories/home:/laktak/Debian_11/amd64/rsyncy_0.2.0-1_amd64.deb
...
# dpkg -i rsyncy_0.2.0-1_amd64.deb
dpkg: error processing archive rsyncy_0.2.0-1_amd64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 rsyncy_0.2.0-1_amd64.deb
```

**Comment by laktak** [comment]
Github does not support arm64 runners directly so I had to find a workaround.

Before I make this available via apt, please test if the following binary works for you:

https://github.com/laktak/rsyncy/actions/runs/7898328626/artifacts/1244047889

(this will download a tar in a zip ... containing the binary) if everything works I'll add it to apt.
