### ISSUE TITLE
Does not work for remote host

### ISSUE THREAD

**Issue by aaravrav** [laktak/rsyncy#13]
Rsyncy has no functionality to handle prompts for password (remote user or private key)

**Comment by laktak** [comment]
Yes, see the README:

## Known Issue when using ssh behind rsync

ssh uses direct TTY access to make sure that the input is indeed issued by an interactive keyboard user (for host keys and passwords). That means that rsyncy does not know that ssh is waiting for input and will draw the status bar over it. You can still enter your password and press enter to continue.

Workaround: connect once to your server via ssh to add it to the known_hosts file.

**Comment by laktak** [comment]
I've implemented a workaround for this.
