### ISSUE TITLE
doesn't work on mac

### ISSUE THREAD

**Issue by hemna** [laktak/rsyncy#2]
rsyncy -av Normal\ SSD waboring@192.168.1.44:/mnt/plex/backup_stuff
rsync: --info=progress2: unknown option
rsync error: syntax or usage error (code 1) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(1337) [client=2.6.9]

**Comment by hemna** [comment]
fwiw, I just did a brew install rsync and it now works.

Great interface!

**Comment by laktak** [comment]
Yes, macOS ships with an old version of rsync from 2006. Glad you got it working!
