### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iomari** [laktak/rsyncy#3]
rsyncy -arv --stats /home/iomari/downloads iomari:/temp/gittemp/
[::::::::::::::::::::::::::::::]   0% |           0 |                | 0:05:08 | scan \                                                        
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(644) [sender=3.1.3]

**Comment by iomari** [comment]
BTW, running the command as rsync works perfectly.

**Comment by laktak** [comment]
I'm unable to reproduce this.
