### ISSUE TITLE
on ubuntu 16.04 with python 3.5 error

### ISSUE THREAD

**Issue by ouboub** [laktak/rsyncy#5]
I am on Ubuntu 16.04 running python3.5, after installing rsyncy
and running rsyncy -a /home/oub/ /media/oub/Linux2Mac/oub/ 
I obtain the following error:
```
 File "/home/oub/.local/bin/rsyncy", line 44
    return f"\033[{(30+col) if col<8 else (90-8+col)}m"
```
Not sure what to do

**Comment by laktak** [comment]
I'm sorry. That feature is not supported by your version of python. I will add this to the setup/readme.
