### ISSUE TITLE
"Command not found"

### ISSUE THREAD

**Issue by robert-kairos** [laktak/rsyncy#6]
Hello.  I am a Linux newbie.  

I successfully installed rsyncy and found it in ~/.local/bin.  When I try to run the command, I get an error that "Command 'rsyncy' not found". 

Thank you.

**Comment by angadschawla** [comment]
@robert-kairos Did you check to see if a) you have added that path to your .bashrc file (if you are using bash) and b) have reloaded the terminal session?
