### ISSUE TITLE
Rsyncy use in lf file manager at bottom line problem

### ISSUE THREAD

**Issue by og900aero** [laktak/rsyncy#9]
I would like to transfer the rsync copy routine of the lf file manager to this rsyncy, because I really like the progress bar and it is useful, but it does not want to work with the existing script, the progress bar is not visible on the bottom line. What can be the solution? I use the following script:

```
cmd paste &{{
    set -- $(cat ~/.local/share/lf/files)
    mode="$1"
    shift
    case "$mode" in
        copy)
            # rsync -ah --info=progress2 -- "$@" . |
            rsyncy -ah -- "$@" . |
            stdbuf -i0 -o0 -e0 tr '\r' '\n' |
            while IFS= read -r line; do
                lf -remote "send $id echo $line"
            done
            ;;
        move) mv -n -- "$@" .;;
    esac
    rm ~/.local/share/lf/files
    cd $PWD
    lf -remote "send clear"
    lf -remote "send load"
}}
```

**Comment by laktak** [comment]
I've played a bit with lf support:
https://github.com/laktak/rsyncy#lf-support

Let me know if it works for you.

**Comment by og900aero** [comment]
> I've played a bit with lf support: https://github.com/laktak/rsyncy#lf-support
> 
> Let me know if it works for you.

Thank u. Work well, but one a little problem. Your example working in foreground: cmd paste-rsync %{{
But doesnt work in background (async mode): cmd paste-rsync &{{

**Comment by laktak** [comment]
Well, `&` does not show messages from background processes at all. But this is related to lf - so it would be better to ask in the lf discussion group...

**Comment by og900aero** [comment]
Ok, thx.
